DELIMITER $$

DROP PROCEDURE IF EXISTS insert_car_models$$

CREATE PROCEDURE insert_car_models()
BEGIN
    INSERT INTO CAR_MODEL (car_model_type, car_model_base, maker_name, fuel_type, seat_count) VALUES
    ('Compact Mini', 'SPARK', 'Chevrolet', 'Gasoline', 4),
    ('Compact Mini', 'MORNING', 'Kia', 'Gasoline', 5),
    ('Compact Mini', 'RAY', 'Kia', 'Gasoline', 5),
    ('Compact Mini', 'CASPER', 'Hyundai', 'Gasoline', 4),
    ('Small', 'AVANTE', 'Hyundai', 'Gasoline', 5),
    ('Small', 'AVANTE', 'Hyundai', 'Hybrid', 5),
    ('Small', 'K3', 'Kia', 'Gasoline', 5),
    ('Medium', 'K5', 'Kia', 'Gasoline', 5),
    ('Medium', 'K5', 'Kia', 'Hybrid', 5),
    ('Medium', 'SONATA', 'Hyundai', 'Gasoline', 5),
    ('Medium', 'SONATA', 'Hyundai', 'Hybrid', 5),
    ('Medium', 'G70', 'Genesis', 'Gasoline', 5),
    ('Upper Medium', 'K8', 'Kia', 'Gasoline', 5),
    ('Upper Medium', 'K8', 'Kia', 'Hybrid', 5),
    ('Upper Medium', 'GRANDEUR', 'Hyundai', 'Gasoline', 5),
    ('Upper Medium', 'GRANDEUR', 'Hyundai', 'Hybrid', 5),
    ('Large', 'G80', 'Genesis', 'Gasoline', 5),
    ('Large', 'G90', 'Genesis', 'Gasoline', 5),
    ('Large', 'K9', 'Kia', 'Gasoline', 5),
    ('Van', 'STARIA', 'Hyundai', 'Diesel', 9),
    ('Van', 'STARIA', 'Hyundai', 'Diesel', 11),
    ('Van', 'CARNIVAL', 'Kia', 'Diesel', 9),
    ('Van', 'CARNIVAL', 'Kia', 'Hybrid', 9),
    ('Van', 'CARNIVAL HI LIMOUSINE', 'Kia', 'Gasoline', 7),
    ('Van', 'CARNIVAL HI LIMOUSINE', 'Kia', 'Gasoline', 9),
    ('Van', 'CARNIVAL HI LIMOUSINE', 'Kia', 'Hybrid', 7),
    ('Van', 'CARNIVAL HI LIMOUSINE', 'Kia', 'Hybrid', 9),
    ('SUV/RV', 'TIVOLI', 'KG Mobility', 'Gasoline', 5),
    ('SUV/RV', 'TORRES 4WD', 'KG Mobility', 'Gasoline', 5),
    ('SUV/RV', 'KONA 4WD', 'Hyundai', 'Gasoline', 5),
    ('SUV/RV', 'NIRO', 'Kia', 'Hybrid', 5),
    ('SUV/RV', 'SELTOS 2WD', 'Kia', 'Gasoline', 5),
    ('SUV/RV', 'SELTOS 4WD', 'Kia', 'Gasoline', 5),
    ('SUV/RV', 'SELTOS 4WD', 'Kia', 'Diesel', 5),
    ('SUV/RV', 'TRAILBLAZER 2WD', 'Chevrolet', 'Gasoline', 5),
    ('SUV/RV', 'SPORTAGE 2WD', 'Kia', 'Gasoline', 5),
    ('SUV/RV', 'SPORTAGE 2WD', 'Hyundai', 'Hybrid', 5),
    ('SUV/RV', 'TUCSON 2WD', 'Hyundai', 'Gasoline', 5),
    ('SUV/RV', 'TUCSON 2WD', 'Hyundai', 'Diesel', 5),
    ('SUV/RV', 'TUCSON 2WD', 'Hyundai', 'Hybrid', 5),
    ('SUV/RV', 'SANTAFE 2WD', 'Hyundai', 'Gasoline', 5),
    ('SUV/RV', 'SANTAFE 2WD', 'Hyundai', 'Hybrid', 5),
    ('SUV/RV', 'SANTAFE 4WD', 'Hyundai', 'Gasoline', 7),
    ('SUV/RV', 'SORENTO 2WD', 'Kia', 'Hybrid', 5),
    ('SUV/RV', 'SORENTO 2WD', 'Kia', 'Diesel', 5),
    ('SUV/RV', 'SORENTO 4WD', 'Kia', 'Diesel', 5),
    ('SUV/RV', 'SORENTO 4WD', 'Kia', 'Hybrid', 6),
    ('SUV/RV', 'SORENTO 4WD', 'Kia', 'Gasoline', 7),
    ('SUV/RV', 'SORENTO 4WD', 'Kia', 'Diesel', 7),
    ('SUV/RV', 'PALISADE 2WD', 'Hyundai', 'Gasoline', 7),
    ('SUV/RV', 'PALISADE 2WD', 'Hyundai', 'Diesel', 7),
    ('SUV/RV', 'PALISADE 2WD', 'Hyundai', 'Gasoline', 9),
    ('SUV/RV', 'PALISADE 4WD', 'Hyundai', 'Gasoline', 7),
    ('SUV/RV', 'GV70 2WD', 'Genesis', 'Gasoline', 5),
    ('SUV/RV', 'GV70 4WD', 'Genesis', 'Gasoline', 5),
    ('SUV/RV', 'GV80 2WD', 'Genesis', 'Gasoline', 5),
    ('SUV/RV', 'GV80 4WD', 'Genesis', 'Diesel', 5),
    ('SUV/RV', 'GV80 4WD', 'Genesis', 'Gasoline', 7),
    ('SUV/RV', 'GV80 4WD', 'Genesis', 'Diesel', 7),
    ('EV', 'RAY', 'Kia', 'Electronic', 5),
    ('EV', 'CASPER', 'Hyundai', 'Electronic', 4),
    ('EV', 'EV3 2WD', 'Kia', 'Electronic', 5),
    ('EV', 'EV6 2WD', 'Kia', 'Electronic', 5),
    ('EV', 'EV9', 'Kia', 'Electronic', 6),
    ('EV', 'EV9', 'Kia', 'Electronic', 7),
    ('EV', 'IONIQ5 2WD', 'Hyundai', 'Electronic', 5),
    ('EV', 'GV70', 'Genesis', 'Electronic', 5);
END$$

DELIMITER ;